import type { Metadata } from "next";
import "./globals.css";
import HeaderComponent from "@/components/header";


export const metadata: Metadata = {
  title: "RagnarokCraft - Página Inicial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"></link>
      </head>
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
